"""
tests/test_sigmund_model_hierarchy.py

Pins the contract that core/llm/llm_providers.json declares chat_sigmund as a
genuinely higher-fidelity LLM lineup than chat_assistant — not merely a
re-ordering of the same models.

Three required assertions (per spec):
  1. The #0 (preferred) model differs between chat_assistant and chat_sigmund.
  2. The #0 model in chat_sigmund is of higher fidelity than chat_assistant's #0.
  3. The two model arrays are not the same set in a different order.

Plus three defensive assertions:
  4. Both task entries actually exist with non-empty `models` arrays.
  5. The arrays go through the live LLMProviderConfig loader path (indirect
     test) and produce the same answer (so the loader's defaults can never
     silently mask a missing config).
  6. Every model named in chat_assistant or chat_sigmund is ranked in
     data/model_hierarchy.json (per spec: an unknown model aborts the test
     and demands human intervention before deployment).

Source of truth for the fidelity ladder is data/model_hierarchy.json,
generated by scripts/probe_models.py from the providers' live model-list
endpoints. The ladder is NOT embedded in this test file — that was the v2
mistake. To regenerate after a new model ships:

    ./scripts/probe_models.py --write

Schema note: llm_providers.json is shaped as
    {
      "providers": { "gemini": {...}, "claude": {...}, "openai": {...} },
      "routing":   { "chat_assistant": {...}, "chat_sigmund": {...}, ... }
    }
…NOT with task entries at the top level. Tests read from cfg["routing"][task].
"""

# Test files use different conventions to library code; pylint relaxations:
#   missing-class-docstring  — test class names ARE the docstring
#   missing-function-docstring — test method names ARE the docstring
#   import-outside-toplevel — methods import lazily to scope mock.patch / defer slow loads
#   redefined-outer-name   — pytest fixture pattern: fixture & param share name
#   unused-argument        — Mock side_effect callbacks take *args, **kwargs they don't read
# pylint: disable=missing-class-docstring,missing-function-docstring,import-outside-toplevel,redefined-outer-name,unused-argument

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest


# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------

_THIS_DIR    = Path(__file__).resolve().parent
_PROJECT_DIR = _THIS_DIR.parent
CONFIG_PATH    = _PROJECT_DIR / "core" / "llm" / "llm_providers.json"
HIERARCHY_PATH = _PROJECT_DIR / "data" / "model_hierarchy.json"

if str(_PROJECT_DIR) not in sys.path:
    sys.path.insert(0, str(_PROJECT_DIR))


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def providers_config() -> dict:
    """Load llm_providers.json directly off disk."""
    if not CONFIG_PATH.exists():
        pytest.fail(f"llm_providers.json not found at {CONFIG_PATH}")
    with CONFIG_PATH.open() as f:
        return json.load(f)


@pytest.fixture(scope="module")
def model_hierarchy() -> dict:
    """Load data/model_hierarchy.json — generated by scripts/probe_models.py."""
    if not HIERARCHY_PATH.exists():
        pytest.fail(
            f"Model hierarchy not found at {HIERARCHY_PATH}. "
            f"Generate it with: ./scripts/probe_models.py --write"
        )
    with HIERARCHY_PATH.open() as f:
        doc = json.load(f)
    if "models" not in doc:
        pytest.fail(f"{HIERARCHY_PATH} is malformed — missing 'models' key")
    return doc


@pytest.fixture(scope="module")
def fidelity_lookup(model_hierarchy) -> dict[str, int]:
    """Flatten the hierarchy into a {model_name: fidelity} dict."""
    return {name: info["fidelity"] for name, info in model_hierarchy["models"].items()}


@pytest.fixture(scope="module")
def assistant_models_direct(providers_config) -> list[str]:
    """chat_assistant.models read directly from JSON."""
    return _extract_models_direct(providers_config, "chat_assistant")


@pytest.fixture(scope="module")
def sigmund_models_direct(providers_config) -> list[str]:
    """chat_sigmund.models read directly from JSON."""
    return _extract_models_direct(providers_config, "chat_sigmund")


@pytest.fixture(scope="module")
def assistant_models_via_loader() -> list[str]:
    """chat_assistant.models loaded through LLMProviderConfig.task_config()."""
    return _extract_models_via_loader("chat_assistant")


@pytest.fixture(scope="module")
def sigmund_models_via_loader() -> list[str]:
    """chat_sigmund.models loaded through LLMProviderConfig.task_config()."""
    return _extract_models_via_loader("chat_sigmund")


# ---------------------------------------------------------------------------
# Extraction helpers
# ---------------------------------------------------------------------------

def _extract_models_direct(cfg: dict, task: str) -> list[str]:
    """Pull task.models out of the raw JSON, traversing the routing section."""
    routing = cfg.get("routing")
    if not routing:
        pytest.fail("'routing' section missing from llm_providers.json")
    if task not in routing:
        pytest.fail(f"Task '{task}' missing from routing section of llm_providers.json")
    models = routing[task].get("models")
    if not models:
        pytest.fail(f"Task '{task}' has no 'models' array (or it is empty)")
    if not isinstance(models, list):
        pytest.fail(f"Task '{task}'.models must be a list, got {type(models).__name__}")
    return models


def _extract_models_via_loader(task: str) -> list[str]:
    """Pull task.models through the live LLMProviderConfig singleton."""
    try:
        from core.llm.config import config as llm_config
    except ImportError as e:
        pytest.fail(f"Could not import core.llm.config: {e}")
    cfg = llm_config.task_config(task)
    return cfg.get("models", [])


# ---------------------------------------------------------------------------
# Defensive scaffolding tests (run first — guard the "real" tests)
# ---------------------------------------------------------------------------

def test_both_tasks_present_with_non_empty_models(
    assistant_models_direct, sigmund_models_direct
):
    """Both task entries exist with non-empty `models` arrays."""
    assert len(assistant_models_direct) >= 1, "chat_assistant.models is empty"
    assert len(sigmund_models_direct)   >= 1, "chat_sigmund.models is empty"


def test_loader_path_matches_direct_path(
    assistant_models_direct, sigmund_models_direct,
    assistant_models_via_loader, sigmund_models_via_loader,
):
    """The LLMProviderConfig loader returns the same arrays as raw JSON.

    Guards against the loader silently substituting _ROUTING_DEFAULTS
    when a task entry is malformed.
    """
    assert assistant_models_direct == assistant_models_via_loader, (
        f"chat_assistant: direct read {assistant_models_direct!r} differs from "
        f"loader read {assistant_models_via_loader!r} — loader is masking the config."
    )
    assert sigmund_models_direct == sigmund_models_via_loader, (
        f"chat_sigmund: direct read {sigmund_models_direct!r} differs from "
        f"loader read {sigmund_models_via_loader!r} — loader is masking the config."
    )


def test_all_models_are_ranked(
    assistant_models_direct, sigmund_models_direct, fidelity_lookup
):
    """Every model named in either array must be ranked in data/model_hierarchy.json.

    Per spec: an unknown model is a human-intervention event. The probe is the
    only thing allowed to add ranks; the test refuses to make routing decisions
    against unranked models. To unblock:
        ./scripts/probe_models.py --write
    …and if probe_models.py itself aborts on the unknown, add a TIER_PATTERN
    or MANUAL_OVERRIDE in scripts/probe_models.py first.
    """
    unranked = [
        m for m in (*assistant_models_direct, *sigmund_models_direct)
        if m not in fidelity_lookup
    ]
    assert not unranked, (
        f"Unranked models in llm_providers.json: {unranked}. "
        f"These cannot be safely fidelity-compared. "
        f"Regenerate the hierarchy: ./scripts/probe_models.py --write"
    )


# ---------------------------------------------------------------------------
# The three required assertions
# ---------------------------------------------------------------------------

def test_preferred_models_differ(assistant_models_direct, sigmund_models_direct):
    """Assertion 1: #0 model differs between standard chat and sigmund chat."""
    assert assistant_models_direct[0] != sigmund_models_direct[0], (
        f"chat_assistant and chat_sigmund both prefer '{assistant_models_direct[0]}' as #0. "
        f"Sigmund is meant to use a *different* (higher-fidelity) preferred model."
    )


def test_sigmund_preferred_is_higher_fidelity(
    assistant_models_direct, sigmund_models_direct, fidelity_lookup
):
    """Assertion 2: sigmund's #0 is strictly higher fidelity than assistant's #0."""
    assistant_top = assistant_models_direct[0]
    sigmund_top   = sigmund_models_direct[0]

    if assistant_top not in fidelity_lookup:
        pytest.fail(
            f"chat_assistant's preferred model '{assistant_top}' is not in the "
            f"hierarchy. Regenerate: ./scripts/probe_models.py --write"
        )
    if sigmund_top not in fidelity_lookup:
        pytest.fail(
            f"chat_sigmund's preferred model '{sigmund_top}' is not in the "
            f"hierarchy. Regenerate: ./scripts/probe_models.py --write"
        )

    f_assistant = fidelity_lookup[assistant_top]
    f_sigmund   = fidelity_lookup[sigmund_top]

    assert f_sigmund > f_assistant, (
        f"chat_sigmund's preferred model '{sigmund_top}' (fidelity {f_sigmund}) "
        f"is not strictly higher fidelity than chat_assistant's preferred model "
        f"'{assistant_top}' (fidelity {f_assistant}). "
        f"Sigmund is the crisis/higher-stakes route — it must use a stronger model."
    )


def test_arrays_are_not_a_rearrangement(
    assistant_models_direct, sigmund_models_direct
):
    """Assertion 3: the two arrays are not the same set in a different order."""
    assert set(assistant_models_direct) != set(sigmund_models_direct), (
        f"chat_assistant and chat_sigmund are using the same set of models "
        f"({sorted(set(assistant_models_direct))}) in different order. "
        f"Sigmund must have at least one model the standard chat does not — "
        f"otherwise it's just chat_assistant with reshuffled failover priorities."
    )
