"""
=============================================================================
Module:        Test — GTIN GS1 Check Digit Validation
Location:      tests/test_luhn.py
Description:   Validates every GTIN exported from the products database
               against the GS1 check digit algorithm.

Prerequisites:
    Run this in MySQL first to export the GTINs:

        SELECT gtin FROM products
        INTO OUTFILE '/var/lib/mysql-files/gtin.txt';

    The file path is the MySQL secure_file_priv default on RHEL/Rocky.

Run:
    python -m pytest tests/test_luhn.py -v -s
    (the -s flag shows the progress meter)
=============================================================================
"""

from __future__ import annotations

import os
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

GTIN_FILE = "/var/lib/mysql-files/gtin.txt"


def _generate_and_validate() -> tuple[int, int, list[str]]:
    """
    1. Remove any existing outfile (MySQL will not overwrite).
    2. Export GTINs via mysql CLI using env vars.
    3. Stream the file, validate each GTIN against GS1 check digit.
    """
    import subprocess
    from utils.gtin import is_valid_gs1

    host   = os.environ.get("DB_HOST", "localhost")
    name   = os.environ.get("DB_NAME", "trigzi")
    user   = os.environ.get("DB_USER", "trigzi")
    passwd = os.environ.get("DB_PASS", "")

    # MySQL will not overwrite an existing file
    if os.path.exists(GTIN_FILE):
        os.remove(GTIN_FILE)

    sql = f"SELECT gtin FROM products INTO OUTFILE '{GTIN_FILE}';"
    result = subprocess.run(
        ["mysql", f"-h{host}", f"-u{user}", f"-p{passwd}", name, "-e", sql],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        raise RuntimeError(f"MySQL export failed: {result.stderr.strip()}")

    # Stream and validate
    total    = 0
    failures = 0
    failing_sample: list[str] = []

    with open(GTIN_FILE, "r") as fh:
        for line in fh:
            gtin = line.strip()
            if not gtin or gtin == "NULL":
                continue

            total += 1

            if total % 100_000 == 0:
                print(f"  ... {total:,} checked, {failures} failures so far", flush=True)

            if not is_valid_gs1(gtin):
                failures += 1
                failing_sample.append(gtin)

    # Write DELETE script for all failing GTINs
    DELETE_FILE = "/var/lib/mysql-files/delete_invalid_gtins.sql"
    if failing_sample:
        with open(DELETE_FILE, "w") as f:
            f.write("-- Invalid GS1 check digit — generated by test_gs1.py\n")
            f.write(f"-- {len(failing_sample):,} of {total:,} GTINs ({len(failing_sample)/total*100:.2f}%)\n\n")
            for g in sorted(failing_sample):
                f.write(f'DELETE FROM products WHERE gtin="{g}";\n')
        print(f"  DELETE script written to {DELETE_FILE}")

    return total, failures, failing_sample


class TestGS1File(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        print(f"\n  Exporting GTINs to {GTIN_FILE} ...")
        cls.total, cls.failures, cls.failing_sample = _generate_and_validate()
        print(f"  Done. {cls.total:,} GTINs checked, {cls.failures:,} failures.")

    def test_file_not_empty(self):
        self.assertGreater(self.total, 0,
            f"No GTINs found in {GTIN_FILE} — was the export empty?")

    def test_all_gtins_pass_gs1(self):
        self.assertEqual(
            self.failures, 0,
            f"{self.failures:,} of {self.total:,} GTINs fail GS1 check digit.\n"
            f"DELETE script written to /var/lib/mysql-files/delete_invalid_gtins.sql"
        )

    def test_coverage_report(self):
        """Informational — always passes, prints the final count."""
        print(f"\n  Validated {self.total:,} GTINs against GS1 check digit algorithm")


class TestGS1Algorithm(unittest.TestCase):
    """Unit tests for is_valid_gs1() — no file or DB needed."""

    def setUp(self):
        from utils.gtin import is_valid_gs1
        self.check = is_valid_gs1

    def test_known_valid_ean13(self):
        valid = [
            "9310077217814",   # Real product from Trigzi scan logs
            "5000112548167",   # Coca-Cola UK
            "0012000161155",   # Pepsi US
            "0000000000000",   # All zeros — valid by GS1
        ]
        for gtin in valid:
            with self.subTest(gtin=gtin):
                self.assertTrue(self.check(gtin), f"Expected valid: {gtin}")

    def test_known_invalid_check_digit(self):
        invalid = [
            "9310077217815",
            "5000112548168",
        ]
        for gtin in invalid:
            with self.subTest(gtin=gtin):
                self.assertFalse(self.check(gtin), f"Expected invalid: {gtin}")

    def test_all_zeros_valid(self):
        self.assertTrue(self.check("0000000000000"))

    def test_single_digit_rejected(self):
        # GS1 requires at least 2 digits (payload + check digit)
        self.assertFalse(self.check("0"))
        self.assertFalse(self.check("1"))
